
def configure(conf): 
    """
    -- python headers 
    -- numpy headers 
    -- c++ compiler
    """
    conf.check_tool('python')  
    conf.check_python_headers()    

def build(bld) :
    bld(features="cxx cshlib pyext",
        source="_fgmm.cpp",
        target="fgmm",
        uselib_local="fgmm",
        install_path = '${PYTHONDIR}')
